spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gogo_new?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gogonew
    password: gogonew