spring:
  datasource:
    url: jdbc:mysql://gogonew-api.capn9lzwwvml.ap-northeast-2.rds.amazonaws.com:3306/gogonew?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}