server:
  shutdown: graceful
  port: 8080

springdoc:
  version: 1.0.0
  packages-to-scan: com.gogonew.api
  swagger-ui:
    path: /docs
  use-fqn: true # InnerClass로 Dto 설정할 경우 동일한 스키마 생성되는것 해결.

spring:
  profiles:
    active: local
    group:
      local:
        - local
      real:
        - real