spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

springdoc:
  version: 1.0.0
  packages-to-scan: com.gogonew.api
  swagger-ui:
    path: /docs
  use-fqn: true # InnerClass로 Dto 설정할 경우 동일한 스키마 생성되는것 해결.